"""create quote_requests table

Revision ID: d7fb23801be4
Revises: d961b53f0835
Create Date: 2026-08-29 11:57:13.003212
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7fb23801be4'
down_revision: Union[str, None] = 'd961b53f0835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('budget_range', sa.String(length=100), nullable=True),
    sa.Column('preferred_deadline', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'REVIEWING', 'QUOTED', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='quotestatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_requests_email'), 'quote_requests', ['email'], unique=False)
    op.create_index(op.f('ix_quote_requests_id'), 'quote_requests', ['id'], unique=False)
    op.create_index(op.f('ix_quote_requests_service_id'), 'quote_requests', ['service_id'], unique=False)
    op.create_index(op.f('ix_quote_requests_status'), 'quote_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_requests_status'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_service_id'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_id'), table_name='quote_requests')
    op.drop_index(op.f('ix_quote_requests_email'), table_name='quote_requests')
    op.drop_table('quote_requests')
    # ### end Alembic commands ###
