"""add tax_rate to invoices

Revision ID: dbf0293e1bd6
Revises: b8c3732280e1
Create Date: 2026-09-10 13:48:35.158719
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dbf0293e1bd6'
down_revision: Union[str, None] = 'b8c3732280e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'tax_rate')
    # ### end Alembic commands ###
