"""create domains table

Revision ID: ee1b297dd2fc
Revises: 70e6dbf312f8
Create Date: 2026-09-30 16:44:41.589689
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee1b297dd2fc'
down_revision: Union[str, None] = '70e6dbf312f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The two values added to NotificationType by the domains module.
NEW_NOTIFICATION_TYPES = ("DOMAIN_REGISTERED", "DOMAIN_STATUS_CHANGED")


def _extend_notification_enum() -> None:
    """
    Teach the notification type column about the two domain events.

    PostgreSQL backs sa.Enum with a native ENUM type, so new values need an
    explicit ALTER TYPE; the COMMIT first is the standard workaround because on
    PostgreSQL before 12 an ADD VALUE cannot run inside a transaction block.

    SQLite needs nothing: SQLAlchemy 2.x defaults Enum to
    create_constraint=False, so the column is a plain VARCHAR with no CHECK, and
    SQLite does not enforce VARCHAR length. Autogenerate proposed an
    alter_column purely because the declared length grew.
    """
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    op.execute("COMMIT")
    for value in NEW_NOTIFICATION_TYPES:
        op.execute(f"ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS '{value}'")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('hosting_account_id', sa.Integer(), nullable=True),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('registrar', sa.String(length=100), nullable=False),
    sa.Column('registration_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'CANCELLED', name='domainstatus'), nullable=False),
    sa.Column('registered_date', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('nameservers', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hosting_account_id'], ['hosting_accounts.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_client_id'), 'domains', ['client_id'], unique=False)
    op.create_index(op.f('ix_domains_domain_name'), 'domains', ['domain_name'], unique=False)
    op.create_index(op.f('ix_domains_expires_at'), 'domains', ['expires_at'], unique=False)
    op.create_index(op.f('ix_domains_hosting_account_id'), 'domains', ['hosting_account_id'], unique=False)
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_invoice_id'), 'domains', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_domains_status'), 'domains', ['status'], unique=False)
    _extend_notification_enum()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domains_status'), table_name='domains')
    op.drop_index(op.f('ix_domains_invoice_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_hosting_account_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_expires_at'), table_name='domains')
    op.drop_index(op.f('ix_domains_domain_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_client_id'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###

    # The two NotificationType values are deliberately left in place: removing a
    # value from a PostgreSQL ENUM means rebuilding the type and rewriting every
    # dependent column, and unused labels are harmless.
