/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Services */
        get: operations["list_services_api_v1_services_get"];
        put?: never;
        /** Create Service */
        post: operations["create_service_api_v1_services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Service */
        get: operations["get_service_api_v1_services__service_id__get"];
        put?: never;
        post?: never;
        /** Delete Service */
        delete: operations["delete_service_api_v1_services__service_id__delete"];
        options?: never;
        head?: never;
        /** Update Service */
        patch: operations["update_service_api_v1_services__service_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_admin_users__user_id__get"];
        put?: never;
        post?: never;
        /** Deactivate User */
        delete: operations["deactivate_user_api_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects (role-scoped) */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create a project (ADMIN or STAFF only) */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Deactivate a project (ADMIN only, soft delete) */
        delete: operations["deactivate_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update a project (ADMIN or STAFF only) */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List project milestones (role-scoped)
         * @description List milestones for a project with authorization checks.
         */
        get: operations["list_milestones_api_v1_projects__project_id__milestones_get"];
        put?: never;
        /**
         * Create a milestone (ADMIN or STAFF only)
         * @description Create a new milestone for a project.
         */
        post: operations["create_milestone_api_v1_projects__project_id__milestones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/milestones/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reorder milestones (ADMIN or STAFF only)
         * @description Reorder milestones using a transaction.
         */
        patch: operations["reorder_milestones_api_v1_projects__project_id__milestones_reorder_patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/milestones/{milestone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single milestone
         * @description Get a single milestone with authorization checks.
         */
        get: operations["get_milestone_api_v1_projects__project_id__milestones__milestone_id__get"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a milestone (ADMIN only)
         * @description Soft-delete (deactivate) a milestone.
         */
        delete: operations["deactivate_milestone_api_v1_projects__project_id__milestones__milestone_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a milestone (ADMIN or STAFF only)
         * @description Update a milestone with validation.
         */
        patch: operations["update_milestone_api_v1_projects__project_id__milestones__milestone_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project progress
         * @description Calculate and return project progress based on milestones.
         */
        get: operations["get_project_progress_api_v1_projects__project_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project files */
        get: operations["list_files_api_v1_projects__project_id__files_get"];
        put?: never;
        /**
         * Upload a project file
         * @description Upload a file to a project. CLIENT may only upload to their own active project.
         */
        post: operations["upload_file_api_v1_projects__project_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get file metadata */
        get: operations["get_file_api_v1_projects__project_id__files__file_id__get"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a project file
         * @description Soft-delete a file. ADMIN can delete any file; STAFF cannot delete (existing
         *     convention, matching milestones); CLIENT may delete only files they uploaded
         *     themselves, within their own project.
         */
        delete: operations["delete_file_api_v1_projects__project_id__files__file_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update file metadata
         * @description Update file metadata (category, description). Never touches the stored binary.
         *
         *     ADMIN/STAFF may update any file's metadata; CLIENT only their own uploads.
         */
        patch: operations["update_file_api_v1_projects__project_id__files__file_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/files/{file_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a project file */
        get: operations["download_file_api_v1_projects__project_id__files__file_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get client dashboard
         * @description Get the client dashboard with summary, recent projects, quotes, and activity.
         */
        get: operations["get_dashboard_api_v1_client_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List client projects
         * @description List all projects belonging to the client.
         */
        get: operations["list_projects_api_v1_client_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a client project
         * @description Get detailed information about a project.
         */
        get: operations["get_project_api_v1_client_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/projects/{project_id}/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project milestones
         * @description Get milestones for a project (active only).
         */
        get: operations["get_milestones_api_v1_client_projects__project_id__milestones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List client quotes
         * @description List all quote requests associated with the client's email.
         */
        get: operations["list_quotes_api_v1_client_quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quote-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List quote requests (ADMIN or STAFF only) */
        get: operations["list_quote_requests_api_v1_quote_requests_get"];
        put?: never;
        /** Submit a quote request (public, no account needed) */
        post: operations["create_quote_request_api_v1_quote_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quote-requests/{quote_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a quote request (ADMIN or STAFF only) */
        get: operations["get_quote_request_api_v1_quote_requests__quote_id__get"];
        put?: never;
        post?: never;
        /** Soft-delete a quote request (ADMIN only) */
        delete: operations["delete_quote_request_api_v1_quote_requests__quote_id__delete"];
        options?: never;
        head?: never;
        /** Update quote status and/or admin notes (ADMIN or STAFF only) */
        patch: operations["update_quote_request_api_v1_quote_requests__quote_id__patch"];
        trace?: never;
    };
    "/api/v1/quote-requests/{quote_id}/create-project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert an ACCEPTED quote request into a project (ADMIN or STAFF only) */
        post: operations["create_project_from_quote_api_v1_quote_requests__quote_id__create_project_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_upload_file_api_v1_projects__project_id__files_post */
        Body_upload_file_api_v1_projects__project_id__files_post: {
            /** File */
            file: string;
            /** @default DOCUMENT */
            category: components["schemas"]["FileCategory"];
            /** Description */
            description?: string | null;
        };
        /**
         * ClientActivityItem
         * @description Recent activity entry.
         */
        ClientActivityItem: {
            /** Type */
            type: string;
            /** Message */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ClientDashboardRead
         * @description Main client dashboard response.
         */
        ClientDashboardRead: {
            user: components["schemas"]["ClientUserRead"];
            summary: components["schemas"]["ClientDashboardSummary"];
            /** Recent Projects */
            recent_projects: components["schemas"]["ClientProjectListItem"][];
            /** Recent Quotes */
            recent_quotes: components["schemas"]["ClientQuoteListItem"][];
            /** Recent Activity */
            recent_activity: components["schemas"]["ClientActivityItem"][];
        };
        /**
         * ClientDashboardSummary
         * @description Summary statistics for client dashboard.
         */
        ClientDashboardSummary: {
            /** Total Projects */
            total_projects: number;
            /** Active Projects */
            active_projects: number;
            /** Completed Projects */
            completed_projects: number;
            /** Pending Quotes */
            pending_quotes: number;
        };
        /**
         * ClientMilestoneListItem
         * @description Milestone info for client view.
         */
        ClientMilestoneListItem: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            status: components["schemas"]["MilestoneStatus"];
            /** Display Order */
            display_order: number;
            /** Due Date */
            due_date: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * ClientProjectDetail
         * @description Detailed project info with milestones summary.
         */
        ClientProjectDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            status: components["schemas"]["ProjectStatus"];
            priority: components["schemas"]["ProjectPriority"];
            /** Budget */
            budget: string | null;
            /** Amount Paid */
            amount_paid: string;
            /** Start Date */
            start_date: string | null;
            /** Deadline */
            deadline: string | null;
            /** Progress Percentage */
            progress_percentage: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ClientProjectListItem
         * @description Lightweight project info for dashboard and list.
         */
        ClientProjectListItem: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            status: components["schemas"]["ProjectStatus"];
            priority: components["schemas"]["ProjectPriority"];
            /** Deadline */
            deadline: string | null;
            /** Progress Percentage */
            progress_percentage: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ClientQuoteListItem
         * @description Safe quote info without admin_notes.
         */
        ClientQuoteListItem: {
            /** Id */
            id: number;
            /** Project Title */
            project_title: string;
            status: components["schemas"]["QuoteStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ClientUserRead
         * @description Basic user info for client dashboard.
         */
        ClientUserRead: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
        };
        /** DashboardStats */
        DashboardStats: {
            users: components["schemas"]["UserStats"];
            services: components["schemas"]["ServiceStats"];
            /**
             * @default {
             *       "total": 0,
             *       "active": 0
             *     }
             */
            projects: components["schemas"]["ProjectStats"];
            /**
             * @default {
             *       "pending": 0
             *     }
             */
            quotes: components["schemas"]["QuoteStats"];
            /**
             * @default {
             *       "pending": 0
             *     }
             */
            invoices: components["schemas"]["InvoiceStats"];
            /**
             * @default {
             *       "active": 0
             *     }
             */
            hosting: components["schemas"]["HostingStats"];
            /**
             * @default {
             *       "products": 0,
             *       "pending_orders": 0
             *     }
             */
            store: components["schemas"]["StoreStats"];
            /**
             * @default {
             *       "open_tickets": 0
             *     }
             */
            support: components["schemas"]["SupportStats"];
        };
        /**
         * FileCategory
         * @enum {string}
         */
        FileCategory: "REQUIREMENT" | "PROPOSAL" | "DESIGN" | "DOCUMENT" | "REPORT" | "IMAGE" | "OTHER";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostingStats */
        HostingStats: {
            /**
             * Active
             * @default 0
             */
            active: number;
        };
        /** InvoiceStats */
        InvoiceStats: {
            /**
             * Pending
             * @default 0
             */
            pending: number;
        };
        /** MilestoneReorderItem */
        MilestoneReorderItem: {
            /** Id */
            id: number;
            /** Display Order */
            display_order: number;
        };
        /** MilestoneReorderRequest */
        MilestoneReorderRequest: {
            /** Milestones */
            milestones: components["schemas"]["MilestoneReorderItem"][];
        };
        /**
         * MilestoneStatus
         * @enum {string}
         */
        MilestoneStatus: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "ON_HOLD" | "CANCELLED";
        /** ProjectCreate */
        ProjectCreate: {
            /** Client Id */
            client_id: number;
            /** Quote Request Id */
            quote_request_id?: number | null;
            /** Service Id */
            service_id?: number | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** @default MEDIUM */
            priority: components["schemas"]["ProjectPriority"];
            /** Budget */
            budget?: number | string | null;
            /** Start Date */
            start_date?: string | null;
            /** Deadline */
            deadline?: string | null;
        };
        /** ProjectFileListItem */
        ProjectFileListItem: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Uploaded By */
            uploaded_by: number;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** File Size */
            file_size: number;
            category: components["schemas"]["FileCategory"];
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectFileRead */
        ProjectFileRead: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Uploaded By */
            uploaded_by: number;
            /** Original Filename */
            original_filename: string;
            /** Content Type */
            content_type: string;
            /** File Size */
            file_size: number;
            category: components["schemas"]["FileCategory"];
            /** Description */
            description: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectFileUpdate */
        ProjectFileUpdate: {
            category?: components["schemas"]["FileCategory"] | null;
            /** Description */
            description?: string | null;
        };
        /** ProjectListItem */
        ProjectListItem: {
            /** Id */
            id: number;
            /** Client Id */
            client_id: number;
            /** Service Id */
            service_id: number | null;
            /** Title */
            title: string;
            status: components["schemas"]["ProjectStatus"];
            priority: components["schemas"]["ProjectPriority"];
            /** Budget */
            budget: string | null;
            /** Amount Paid */
            amount_paid: string;
            /** Deadline */
            deadline: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectMilestoneCreate */
        ProjectMilestoneCreate: {
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default PENDING */
            status: components["schemas"]["MilestoneStatus"];
            /** Display Order */
            display_order?: number | null;
            /** Start Date */
            start_date?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /** ProjectMilestoneListItem */
        ProjectMilestoneListItem: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            status: components["schemas"]["MilestoneStatus"];
            /** Display Order */
            display_order: number;
            /** Start Date */
            start_date: string | null;
            /** Due Date */
            due_date: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectMilestoneRead */
        ProjectMilestoneRead: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            status: components["schemas"]["MilestoneStatus"];
            /** Display Order */
            display_order: number;
            /** Start Date */
            start_date: string | null;
            /** Due Date */
            due_date: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectMilestoneUpdate */
        ProjectMilestoneUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            status?: components["schemas"]["MilestoneStatus"] | null;
            /** Display Order */
            display_order?: number | null;
            /** Start Date */
            start_date?: string | null;
            /** Due Date */
            due_date?: string | null;
        };
        /**
         * ProjectPriority
         * @enum {string}
         */
        ProjectPriority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
        /** ProjectProgressRead */
        ProjectProgressRead: {
            /** Project Id */
            project_id: number;
            /** Total Milestones */
            total_milestones: number;
            /** Completed Milestones */
            completed_milestones: number;
            /** In Progress Milestones */
            in_progress_milestones: number;
            /** Pending Milestones */
            pending_milestones: number;
            /** Progress Percentage */
            progress_percentage: number;
        };
        /** ProjectRead */
        ProjectRead: {
            /** Id */
            id: number;
            /** Client Id */
            client_id: number;
            /** Quote Request Id */
            quote_request_id: number | null;
            /** Service Id */
            service_id: number | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            status: components["schemas"]["ProjectStatus"];
            priority: components["schemas"]["ProjectPriority"];
            /** Budget */
            budget: string | null;
            /** Amount Paid */
            amount_paid: string;
            /** Start Date */
            start_date: string | null;
            /** Deadline */
            deadline: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectStats */
        ProjectStats: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Active
             * @default 0
             */
            active: number;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "PENDING" | "PLANNING" | "IN_PROGRESS" | "ON_HOLD" | "TESTING" | "CLIENT_REVIEW" | "COMPLETED" | "CANCELLED";
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
            priority?: components["schemas"]["ProjectPriority"] | null;
            /** Budget */
            budget?: number | string | null;
            /** Amount Paid */
            amount_paid?: number | string | null;
            /** Start Date */
            start_date?: string | null;
            /** Deadline */
            deadline?: string | null;
        };
        /** QuoteRequestAdminUpdate */
        QuoteRequestAdminUpdate: {
            status?: components["schemas"]["QuoteStatus"] | null;
            /** Admin Notes */
            admin_notes?: string | null;
        };
        /** QuoteRequestCreate */
        QuoteRequestCreate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            /** Company Name */
            company_name?: string | null;
            /** Service Id */
            service_id?: number | null;
            /** Project Title */
            project_title: string;
            /** Project Description */
            project_description: string;
            /** Budget Range */
            budget_range?: string | null;
            /** Preferred Deadline */
            preferred_deadline?: string | null;
        };
        /** QuoteRequestPublicRead */
        QuoteRequestPublicRead: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            /** Company Name */
            company_name: string | null;
            /** Service Id */
            service_id: number | null;
            /** Project Title */
            project_title: string;
            /** Project Description */
            project_description: string;
            /** Budget Range */
            budget_range: string | null;
            /** Preferred Deadline */
            preferred_deadline: string | null;
            status: components["schemas"]["QuoteStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuoteRequestRead */
        QuoteRequestRead: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            /** Company Name */
            company_name: string | null;
            /** Service Id */
            service_id: number | null;
            /** Project Title */
            project_title: string;
            /** Project Description */
            project_description: string;
            /** Budget Range */
            budget_range: string | null;
            /** Preferred Deadline */
            preferred_deadline: string | null;
            status: components["schemas"]["QuoteStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Admin Notes */
            admin_notes: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QuoteStats */
        QuoteStats: {
            /**
             * Pending
             * @default 0
             */
            pending: number;
        };
        /**
         * QuoteStatus
         * @enum {string}
         */
        QuoteStatus: "NEW" | "REVIEWING" | "QUOTED" | "ACCEPTED" | "REJECTED" | "CANCELLED";
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "ADMIN" | "STAFF" | "CLIENT";
        /** ServiceCreate */
        ServiceCreate: {
            /** Name */
            name: string;
            /** Short Description */
            short_description?: string | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Icon */
            icon?: string | null;
            /** Image */
            image?: string | null;
            /** Price From */
            price_from?: number | string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Display Order
             * @default 0
             */
            display_order: number;
            /** Slug */
            slug?: string | null;
        };
        /** ServiceRead */
        ServiceRead: {
            /** Name */
            name: string;
            /** Short Description */
            short_description?: string | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Icon */
            icon?: string | null;
            /** Image */
            image?: string | null;
            /** Price From */
            price_from?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Display Order
             * @default 0
             */
            display_order: number;
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ServiceStats */
        ServiceStats: {
            /** Total */
            total: number;
            /** Active */
            active: number;
        };
        /** ServiceUpdate */
        ServiceUpdate: {
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
            /** Short Description */
            short_description?: string | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Icon */
            icon?: string | null;
            /** Image */
            image?: string | null;
            /** Price From */
            price_from?: number | string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Display Order */
            display_order?: number | null;
        };
        /** StoreStats */
        StoreStats: {
            /**
             * Products
             * @default 0
             */
            products: number;
            /**
             * Pending Orders
             * @default 0
             */
            pending_orders: number;
        };
        /** SupportStats */
        SupportStats: {
            /**
             * Open Tickets
             * @default 0
             */
            open_tickets: number;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserAdminUpdate */
        UserAdminUpdate: {
            role?: components["schemas"]["Role"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** UserCreate */
        UserCreate: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /** Full Name */
            full_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone?: string | null;
            /** Id */
            id: number;
            role: components["schemas"]["Role"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserStats */
        UserStats: {
            /** Total */
            total: number;
            /** Clients */
            clients: number;
            /** Staff */
            staff: number;
            /** Admins */
            admins: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_services_api_v1_services_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                category?: string | null;
                search?: string | null;
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_service_api_v1_services_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_service_api_v1_services__service_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_service_api_v1_services__service_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_service_api_v1_services__service_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_admin_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string | null;
                role?: components["schemas"]["Role"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_api_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: components["schemas"]["ProjectStatus"] | null;
                priority?: components["schemas"]["ProjectPriority"] | null;
                service_id?: number | null;
                client_id?: number | null;
                search?: string | null;
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_milestones_api_v1_projects__project_id__milestones_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["MilestoneStatus"] | null;
                include_inactive?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMilestoneListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_milestone_api_v1_projects__project_id__milestones_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMilestoneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMilestoneRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_milestones_api_v1_projects__project_id__milestones_reorder_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MilestoneReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_milestone_api_v1_projects__project_id__milestones__milestone_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                milestone_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMilestoneRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_milestone_api_v1_projects__project_id__milestones__milestone_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                milestone_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMilestoneRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_milestone_api_v1_projects__project_id__milestones__milestone_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                milestone_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMilestoneUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMilestoneRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_progress_api_v1_projects__project_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectProgressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_api_v1_projects__project_id__files_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["FileCategory"] | null;
                include_inactive?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_v1_projects__project_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_v1_projects__project_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_v1_projects__project_id__files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_api_v1_projects__project_id__files__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_file_api_v1_projects__project_id__files__file_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                file_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectFileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_api_v1_projects__project_id__files__file_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_v1_client_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDashboardRead"];
                };
            };
        };
    };
    list_projects_api_v1_client_projects_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProjectStatus"] | null;
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientProjectListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_client_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientProjectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_milestones_api_v1_client_projects__project_id__milestones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientMilestoneListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quotes_api_v1_client_quotes_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["QuoteStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientQuoteListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quote_requests_api_v1_quote_requests_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: components["schemas"]["QuoteStatus"] | null;
                service_id?: number | null;
                search?: string | null;
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteRequestRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_quote_request_api_v1_quote_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteRequestPublicRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_request_api_v1_quote_requests__quote_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteRequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_quote_request_api_v1_quote_requests__quote_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteRequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_quote_request_api_v1_quote_requests__quote_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequestAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteRequestRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_from_quote_api_v1_quote_requests__quote_id__create_project_post: {
        parameters: {
            query?: {
                /** @description User id of the client who owns the resulting project. If omitted, an active CLIENT account matching the quote's email is used; required if none matches (quote requests don't require an account, so there may be no automatic match). */
                client_id?: number | null;
            };
            header?: never;
            path: {
                quote_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
